# Generated by Django 3.2.16 on 2022-10-13 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(verbose_name='chat id')),
                ('sex', models.PositiveIntegerField(choices=[(1, 'Жінка'), (2, 'Чоловік')], verbose_name='Стать')),
                ('city', models.CharField(max_length=200, verbose_name='Місто')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_temp', models.FloatField(verbose_name='Мінімальна температура')),
                ('max_temp', models.FloatField(verbose_name='Максимальна температура')),
                ('sex', models.PositiveIntegerField(choices=[(1, 'Жінка'), (2, 'Чоловік')], verbose_name='Стать')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.photocollection')),
            ],
        ),
    ]
