# Generated by Django 3.2.16 on 2022-10-24 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_temp', models.FloatField(verbose_name='Мінімальна температура')),
                ('max_temp', models.FloatField(verbose_name='Максимальна температура')),
                ('sex', models.PositiveIntegerField(choices=[(1, 'Жінка'), (2, 'Чоловік')], verbose_name='Стать')),
                ('wind', models.IntegerField(verbose_name='Швідкість вітру')),
                ('rain', models.IntegerField(verbose_name='Інтенсівнисть дощу')),
            ],
        ),
        migrations.RemoveField(
            model_name='photocollectionitem',
            name='collection',
        ),
        migrations.AlterField(
            model_name='person',
            name='chat_id',
            field=models.PositiveIntegerField(verbose_name='chat id'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.PositiveIntegerField(choices=[(1, 'Woman'), (2, 'Men')], verbose_name='Стать'),
        ),
        migrations.DeleteModel(
            name='PhotoCollection',
        ),
        migrations.DeleteModel(
            name='PhotoCollectionItem',
        ),
        migrations.AddField(
            model_name='item',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.itemsset'),
        ),
    ]
